package de.jonas_thelemann.uni.gosoan.model

data class GosoanSensorEvent constructor(
    val sensorType: Int,
    val sensorName: String,
    val values: FloatArray,
    val accuracy: Int,
    val timestamp: Long,
) {
    // Recommended equals and hashCode definitions, autogenerated.
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as GosoanSensorEvent

        if (!values.contentEquals(other.values)) return false

        return true
    }

    override fun hashCode(): Int {
        return values.contentHashCode()
    }
}