package de.jonas_thelemann.uni.gosoan.model

data class GosoanSensorEvent constructor(
    private val accuracy: Int,
    // id would require API level 24
    private val name: String,
    private val timestamp: Long,
    private val type: Int,
    private val values: FloatArray
) {
    // Recommended equals and hashCode definitions, autogenerated.
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as GosoanSensorEvent

        if (!values.contentEquals(other.values)) return false

        return true
    }

    override fun hashCode(): Int {
        return values.contentHashCode()
    }
}